apiVersion: tf.kubeform.com/v1alpha1
kind: Module
metadata:
  name: aws-s3-module-sample
spec:
  resource:
    input:
      bucket: "kubeform-module"
      forceDestroy: true
  moduleDef: demo-module-def
  providerRef:
    name: aws-credentials
